name: Multi-API Report (Daily + Saturday)

on:
  schedule:
    # 1) Every day at 1:00 AM IST
    - cron: "30 19 * * *"  # 01:00 IST daily (GitHub cron uses UTC)

    # 2) Every Saturday at 6:00 PM IST
    - cron: "30 12 * * 6"  # 18:00 IST Saturday (GitHub cron uses UTC)

  # Manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run parent report script
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL:  ${{ secrets.TO_EMAIL }}

          API1_URL:  ${{ secrets.API1_URL }}
          API2_URL:  ${{ secrets.API2_URL }}
          API3_URL:  ${{ secrets.API3_URL }}
          API_KEY:   ${{ secrets.API_KEY }}
        run: python report_parent.py

      - name: Upload error log (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ErrorLog
          path: error.log
          if-no-files-found: ignore
